# Ruby のベースイメージを指定
FROM ruby:3.4.8

# 環境変数の設定
ENV LANG C.UTF-8  # 日本語対応
ENV TZ Asia/Tokyo # タイムゾーンを日本に設定

# 必要なパッケージのインストール
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    git \
    vim \
    nodejs \
    npm \
    && npm install -g yarn \
    && npm install -g esbuild \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリの作成
RUN mkdir /myapp
WORKDIR /myapp

# GemfileとGemfile.lockをコピー
COPY Gemfile Gemfile.lock ./

# Bundlerのインストール
RUN gem install bundler
RUN bundle install

# アプリケーションのコードをコピー
COPY . .

# アプリケーションのコードをコピー
# COPY . /myapp